
import React, { useState, useEffect } from 'react';
import { Copy, Check, RefreshCw, Calculator, Download, AlertCircle, DollarSign, Percent, TrendingUp, ArrowRightLeft, Globe, Binary } from 'lucide-react';

// --- HEALTH ---
export const BMICalculator: React.FC = () => {
  const [unit, setUnit] = useState<'metric' | 'imperial'>('metric');
  
  // Inputs
  const [weight, setWeight] = useState<string>(''); 
  const [height, setHeight] = useState<string>(''); // cm
  const [heightFt, setHeightFt] = useState<string>('');
  const [heightIn, setHeightIn] = useState<string>('');
  
  // Results
  const [bmi, setBmi] = useState<number | null>(null);
  const [category, setCategory] = useState<string>('');
  const [resultColor, setResultColor] = useState<string>('bg-slate-50');
  const [error, setError] = useState<string>('');
  const [copied, setCopied] = useState(false);

  const calculate = () => {
    setError('');
    setBmi(null);

    const w = parseFloat(weight);
    if (isNaN(w) || w <= 0) {
        setError('Please enter a valid positive weight.');
        return;
    }

    let calculatedBMI = 0;

    if (unit === 'metric') {
        const hCm = parseFloat(height);
        if (isNaN(hCm) || hCm <= 0) {
            setError('Please enter a valid positive height.');
            return;
        }
        const hM = hCm / 100; // convert to meters
        calculatedBMI = w / (hM * hM);
    } else {
        const ft = parseFloat(heightFt) || 0;
        const inch = parseFloat(heightIn) || 0;
        if ((ft === 0 && inch === 0) || ft < 0 || inch < 0) {
            setError('Please enter a valid positive height.');
            return;
        }
        const totalInches = (ft * 12) + inch;
        // Imperial Formula: 703 x weight (lbs) / [height (in)]^2
        calculatedBMI = (w / (totalInches * totalInches)) * 703;
    }

    setBmi(calculatedBMI);

    // Determine Category and Color
    if (calculatedBMI < 18.5) {
        setCategory('Underweight');
        setResultColor('bg-blue-50 text-blue-700 border-blue-200');
    } else if (calculatedBMI < 25) {
        setCategory('Normal Weight');
        setResultColor('bg-green-50 text-green-700 border-green-200');
    } else if (calculatedBMI < 30) {
        setCategory('Overweight');
        setResultColor('bg-orange-50 text-orange-700 border-orange-200');
    } else {
        setCategory('Obese');
        setResultColor('bg-red-50 text-red-700 border-red-200');
    }
  };

  const reset = () => {
    setWeight('');
    setHeight('');
    setHeightFt('');
    setHeightIn('');
    setBmi(null);
    setError('');
    setResultColor('bg-slate-50');
    setCategory('');
  };

  const handleDownload = () => {
      if (!bmi) return;
      const hDisplay = unit === 'metric' ? `${height} cm` : `${heightFt || 0}' ${heightIn || 0}"`;
      const wDisplay = `${weight} ${unit === 'metric' ? 'kg' : 'lbs'}`;
      const text = `BMI Report\n==========\nWeight: ${wDisplay}\nHeight: ${hDisplay}\n\nBMI Result: ${bmi.toFixed(2)}\nCategory: ${category}\n\nGenerated by ToolMaster Pro`;
      
      const blob = new Blob([text], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'bmi-report.txt';
      a.click();
      URL.revokeObjectURL(url);
  };

  return (
    <div className="grid md:grid-cols-2 gap-8">
      {/* Inputs Panel */}
      <div className="space-y-6">
         {/* Unit Selector */}
         <div className="flex bg-slate-100 p-1 rounded-lg">
            <button 
                onClick={() => {setUnit('metric'); reset()}} 
                className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${unit === 'metric' ? 'bg-white text-brand-600 shadow-sm ring-1 ring-slate-200' : 'text-slate-500 hover:text-slate-700'}`}
            >
                Metric (kg / cm)
            </button>
            <button 
                onClick={() => {setUnit('imperial'); reset()}} 
                className={`flex-1 py-2 text-sm font-medium rounded-md transition-all ${unit === 'imperial' ? 'bg-white text-brand-600 shadow-sm ring-1 ring-slate-200' : 'text-slate-500 hover:text-slate-700'}`}
            >
                Imperial (lbs / ft)
            </button>
         </div>

         {/* Weight Input */}
         <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Weight ({unit === 'metric' ? 'kg' : 'lbs'})</label>
            <input 
                type="number" 
                value={weight}
                onChange={(e) => setWeight(e.target.value)}
                className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition placeholder:text-slate-300"
                placeholder={unit === 'metric' ? 'e.g. 70' : 'e.g. 154'}
                min="0"
            />
         </div>

         {/* Height Input */}
         <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Height</label>
            {unit === 'metric' ? (
                <div className="relative">
                    <input 
                        type="number" 
                        value={height}
                        onChange={(e) => setHeight(e.target.value)}
                        className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition placeholder:text-slate-300"
                        placeholder="e.g. 175"
                        min="0"
                    />
                    <span className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm font-medium bg-white px-1">cm</span>
                </div>
            ) : (
                <div className="flex gap-4">
                    <div className="relative flex-1">
                        <input 
                            type="number" 
                            value={heightFt}
                            onChange={(e) => setHeightFt(e.target.value)}
                            className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none placeholder:text-slate-300"
                            placeholder="5"
                            min="0"
                        />
                        <span className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm font-medium bg-white px-1">ft</span>
                    </div>
                    <div className="relative flex-1">
                        <input 
                            type="number" 
                            value={heightIn}
                            onChange={(e) => setHeightIn(e.target.value)}
                            className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none placeholder:text-slate-300"
                            placeholder="9"
                            min="0"
                        />
                        <span className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 text-sm font-medium bg-white px-1">in</span>
                    </div>
                </div>
            )}
         </div>

         {/* Error Message */}
         {error && (
            <div className="flex items-center gap-2 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-100 animate-in fade-in slide-in-from-top-1">
                <AlertCircle className="w-4 h-4 shrink-0" /> {error}
            </div>
         )}

         {/* Action Buttons */}
         <div className="flex gap-3 pt-2">
            <button 
                onClick={calculate} 
                className="flex-1 bg-brand-600 text-white py-3 rounded-lg font-bold hover:bg-brand-700 transition-all flex items-center justify-center gap-2 shadow-lg hover:shadow-brand-200 active:scale-[0.98]"
            >
                <Calculator className="w-4 h-4" /> Calculate BMI
            </button>
            <button 
                onClick={reset} 
                className="px-4 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 transition hover:text-slate-800 border border-slate-200" 
                title="Reset Inputs"
            >
                <RefreshCw className="w-5 h-5" />
            </button>
         </div>
      </div>

      {/* Results Panel */}
      <div className={`rounded-xl p-8 border flex flex-col items-center justify-center text-center transition-all duration-500 ${bmi ? resultColor : 'bg-slate-50 border-slate-200'}`}>
          {bmi ? (
            <div className="animate-in fade-in zoom-in duration-300 w-full">
                <h3 className="text-lg font-medium opacity-80 mb-4">Your BMI Score</h3>
                <div className="text-6xl font-extrabold tracking-tight mb-4">{bmi.toFixed(1)}</div>
                <div className="inline-block px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wide bg-white/60 border border-black/5 shadow-sm mb-8">
                    {category}
                </div>
                
                <div className="flex gap-3 justify-center border-t border-black/5 pt-6 mt-2">
                    <button 
                        onClick={() => {
                            navigator.clipboard.writeText(`BMI: ${bmi.toFixed(1)} - ${category}`);
                            setCopied(true);
                            setTimeout(() => setCopied(false), 2000);
                        }}
                        className="flex items-center gap-2 text-sm font-medium opacity-70 hover:opacity-100 transition bg-white/50 px-3 py-1.5 rounded hover:bg-white"
                    >
                        {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />} {copied ? 'Copied' : 'Copy'}
                    </button>
                    <button 
                        onClick={handleDownload} 
                        className="flex items-center gap-2 text-sm font-medium opacity-70 hover:opacity-100 transition bg-white/50 px-3 py-1.5 rounded hover:bg-white"
                    >
                        <Download className="w-4 h-4" /> Save Report
                    </button>
                </div>
            </div>
          ) : (
            <div className="text-slate-400">
                <Calculator className="w-16 h-16 mx-auto mb-4 opacity-20" />
                <p className="text-lg font-medium text-slate-500">Ready to Calculate</p>
                <p className="text-sm mt-2 max-w-[200px] mx-auto opacity-75">Enter your weight and height details to see your health status.</p>
            </div>
          )}
      </div>
    </div>
  );
};

// --- DATE ---
export const AgeCalculator: React.FC = () => {
  const [dob, setDob] = useState('');
  const [age, setAge] = useState({ y: 0, m: 0, d: 0 });

  const calculate = () => {
    if (!dob) return;
    const birth = new Date(dob);
    const now = new Date();
    let y = now.getFullYear() - birth.getFullYear();
    let m = now.getMonth() - birth.getMonth();
    let d = now.getDate() - birth.getDate();
    if (d < 0) { m--; d += 30; }
    if (m < 0) { y--; m += 12; }
    setAge({ y, m, d });
  };

  return (
    <div className="space-y-6 max-w-md mx-auto">
      <div><label className="block text-sm font-medium mb-1">Date of Birth</label><input type="date" value={dob} onChange={e=>setDob(e.target.value)} className="w-full p-3 border rounded-lg"/></div>
      <button onClick={calculate} className="w-full bg-brand-600 text-white py-2 rounded-lg hover:bg-brand-700">Calculate Age</button>
      {age.y > 0 && (
        <div className="flex justify-between text-center bg-slate-100 p-4 rounded-lg">
          <div><div className="text-2xl font-bold">{age.y}</div><div className="text-xs uppercase text-slate-500">Years</div></div>
          <div><div className="text-2xl font-bold">{age.m}</div><div className="text-xs uppercase text-slate-500">Months</div></div>
          <div><div className="text-2xl font-bold">{age.d}</div><div className="text-xs uppercase text-slate-500">Days</div></div>
        </div>
      )}
    </div>
  );
};

export const DateDiffCalculator: React.FC = () => {
    const [start, setStart] = useState('');
    const [end, setEnd] = useState('');
    const [diff, setDiff] = useState<number | null>(null);
    
    const calc = () => {
        if(start && end) {
            const d1 = new Date(start);
            const d2 = new Date(end);
            setDiff(Math.abs(d2.getTime() - d1.getTime()));
        }
    }

    return (
        <div className="grid md:grid-cols-2 gap-4">
            <div><label className="block text-sm mb-1">Start Date</label><input type="date" value={start} onChange={e=>setStart(e.target.value)} className="w-full p-2 border rounded"/></div>
            <div><label className="block text-sm mb-1">End Date</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="w-full p-2 border rounded"/></div>
            <button onClick={calc} className="md:col-span-2 bg-brand-600 text-white py-2 rounded">Calculate Difference</button>
            {diff !== null && (
                <div className="md:col-span-2 bg-slate-50 p-4 rounded text-center">
                    <p className="font-bold text-xl">{Math.floor(diff / (1000 * 60 * 60 * 24))} Days</p>
                    <p className="text-sm text-slate-500">or {Math.floor(diff / (1000 * 60 * 60))} Hours</p>
                </div>
            )}
        </div>
    )
}

// --- FINANCE ---

const PayPalCalculator: React.FC = () => {
  const [amount, setAmount] = useState<number | ''>(100);
  const [currency, setCurrency] = useState('USD');
  const [type, setType] = useState<'business' | 'personal'>('business');
  const [payer, setPayer] = useState<'receiver' | 'sender'>('receiver');
  const [copied, setCopied] = useState(false);

  const CURRENCIES: Record<string, { s: string, f: number, label: string }> = {
    USD: { s: '$', f: 0.49, label: 'USD - US Dollar' },
    EUR: { s: '€', f: 0.35, label: 'EUR - Euro' },
    GBP: { s: '£', f: 0.30, label: 'GBP - British Pound' },
    CAD: { s: 'C$', f: 0.30, label: 'CAD - Canadian Dollar' },
    AUD: { s: 'A$', f: 0.30, label: 'AUD - Australian Dollar' },
    JPY: { s: '¥', f: 40, label: 'JPY - Japanese Yen' },
    INR: { s: '₹', f: 3, label: 'INR - Indian Rupee' },
    PKR: { s: '₨', f: 5, label: 'PKR - Pakistani Rupee' },
    BRL: { s: 'R$', f: 0.60, label: 'BRL - Brazilian Real' },
    SGD: { s: 'S$', f: 0.50, label: 'SGD - Singapore Dollar' },
    MXN: { s: 'MX$', f: 4.00, label: 'MXN - Mexican Peso' },
  };

  // Rates
  const [ratePct, setRatePct] = useState(3.49);
  const [rateFix, setRateFix] = useState(0.49);

  // Update defaults
  useEffect(() => {
    setRateFix(CURRENCIES[currency]?.f || 0.49);
  }, [currency]);

  useEffect(() => {
    if (type === 'business') setRatePct(3.49);
    else setRatePct(2.99); 
  }, [type]);

  // Calc
  const val = typeof amount === 'number' ? Math.max(0, amount) : 0;
  let total = 0, fee = 0, net = 0;
  
  if (val > 0) {
      const r = ratePct / 100;
      if (payer === 'receiver') {
          // Sender sends `val`. Fees deducted. Receiver gets `net`.
          total = val;
          fee = (val * r) + rateFix;
          net = val - fee;
      } else {
          // Receiver must get `val`. Fees added on top. Sender sends `total`.
          net = val;
          // Formula: total - (total*r + fix) = val  =>  total(1-r) = val + fix
          if (r >= 1) total = 0; // Edge case prevent division error
          else total = (val + rateFix) / (1 - r);
          fee = total - val;
      }
  }

  // Safety clamp
  if (net < 0) net = 0;
  if (fee < 0) fee = 0;

  const sym = CURRENCIES[currency]?.s || '$';
  const fmt = (n: number) => n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const handleCopy = () => {
      const txt = `Amount: ${sym}${fmt(val)}\nFee: ${sym}${fmt(fee)}\nTotal: ${sym}${fmt(total)}\nNet: ${sym}${fmt(net)}`;
      navigator.clipboard.writeText(txt);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-2xl mx-auto bg-white p-6 rounded-xl border border-slate-200 space-y-6">
        {/* Inputs */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Amount to {payer === 'receiver' ? 'Send' : 'Receive'}</label>
                <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500">{sym}</span>
                    <input 
                        type="number" 
                        value={amount} 
                        onChange={e => setAmount(e.target.value === '' ? '' : parseFloat(e.target.value))}
                        className="w-full pl-8 pr-4 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                        placeholder="0.00"
                        min="0"
                    />
                </div>
            </div>
            <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Currency</label>
                <select 
                    value={currency} 
                    onChange={e => setCurrency(e.target.value)}
                    className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none bg-slate-50"
                >
                    {Object.entries(CURRENCIES).map(([code, conf]) => (
                        <option key={code} value={code}>{conf.label}</option>
                    ))}
                </select>
            </div>
        </div>

        {/* Options */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-4 bg-slate-50 rounded-lg border border-slate-100">
             <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Payment Type</label>
                <div className="flex bg-white rounded-lg p-1 border border-slate-200">
                    <button onClick={() => setType('business')} className={`flex-1 py-1.5 text-sm font-medium rounded-md transition ${type === 'business' ? 'bg-brand-100 text-brand-700' : 'text-slate-600 hover:bg-slate-50'}`}>Business</button>
                    <button onClick={() => setType('personal')} className={`flex-1 py-1.5 text-sm font-medium rounded-md transition ${type === 'personal' ? 'bg-brand-100 text-brand-700' : 'text-slate-600 hover:bg-slate-50'}`}>Personal</button>
                </div>
             </div>
             <div>
                <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Fee Payer</label>
                <div className="flex bg-white rounded-lg p-1 border border-slate-200">
                    <button onClick={() => setPayer('receiver')} className={`flex-1 py-1.5 text-sm font-medium rounded-md transition ${payer === 'receiver' ? 'bg-brand-100 text-brand-700' : 'text-slate-600 hover:bg-slate-50'}`}>Receiver</button>
                    <button onClick={() => setPayer('sender')} className={`flex-1 py-1.5 text-sm font-medium rounded-md transition ${payer === 'sender' ? 'bg-brand-100 text-brand-700' : 'text-slate-600 hover:bg-slate-50'}`}>Sender</button>
                </div>
             </div>
             
             {/* Manual Override */}
             <div className="col-span-1 md:col-span-2 flex gap-4 items-center mt-2 pt-2 border-t border-slate-200">
                <div className="flex-1">
                    <label className="block text-xs text-slate-500 mb-1">Fee %</label>
                    <input type="number" value={ratePct} onChange={e=>setRatePct(parseFloat(e.target.value)||0)} className="w-full p-1.5 border border-slate-200 rounded text-sm" step="0.01"/>
                </div>
                <div className="flex-1">
                    <label className="block text-xs text-slate-500 mb-1">Fixed Fee</label>
                    <div className="relative">
                        <span className="absolute left-2 top-1/2 -translate-y-1/2 text-xs text-slate-400">{sym}</span>
                        <input type="number" value={rateFix} onChange={e=>setRateFix(parseFloat(e.target.value)||0)} className="w-full pl-6 pr-2 py-1.5 border border-slate-200 rounded text-sm" step="0.01"/>
                    </div>
                </div>
             </div>
        </div>

        {/* Results */}
        <div className="bg-slate-900 text-white p-6 rounded-xl relative overflow-hidden">
            <div className="grid grid-cols-3 gap-4 text-center relative z-10">
                <div>
                    <p className="text-slate-400 text-xs uppercase tracking-wider mb-1">Total Amount</p>
                    <p className="text-xl font-bold">{sym}{fmt(total)}</p>
                </div>
                <div>
                    <p className="text-slate-400 text-xs uppercase tracking-wider mb-1">Fee</p>
                    <p className="text-xl font-bold text-red-400">-{sym}{fmt(fee)}</p>
                </div>
                <div>
                    <p className="text-slate-400 text-xs uppercase tracking-wider mb-1">Net Received</p>
                    <p className="text-xl font-bold text-green-400">{sym}{fmt(net)}</p>
                </div>
            </div>
            
            <button 
                onClick={handleCopy}
                className="mt-6 w-full flex items-center justify-center gap-2 bg-white/10 hover:bg-white/20 py-2 rounded-lg transition text-sm font-medium"
            >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy Results'}
            </button>
        </div>
    </div>
  );
};

export const DiscountCalculator: React.FC = () => {
  const [price, setPrice] = useState('');
  const [discount, setDiscount] = useState('');
  const [finalPrice, setFinalPrice] = useState(0);
  const [saved, setSaved] = useState(0);
  const [error, setError] = useState('');

  useEffect(() => {
    const p = parseFloat(price);
    const d = parseFloat(discount);

    if (price === '' || discount === '') {
        setFinalPrice(0);
        setSaved(0);
        setError('');
        return;
    }

    if (isNaN(p) || p < 0) {
        setError('Invalid price');
        return;
    }
    if (isNaN(d) || d < 0 || d > 100) {
        setError('Invalid discount (0-100)');
        return;
    }

    setError('');
    const s = p * (d / 100);
    setSaved(s);
    setFinalPrice(p - s);
  }, [price, discount]);

  return (
    <div className="max-w-2xl mx-auto grid md:grid-cols-2 gap-8">
        <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm space-y-4">
            <div>
                <label className="block text-sm font-medium mb-1">Original Price ($)</label>
                <input type="number" value={price} onChange={e=>setPrice(e.target.value)} className="w-full p-3 border rounded-lg outline-none focus:ring-2 focus:ring-brand-500" placeholder="100.00"/>
            </div>
            <div>
                <label className="block text-sm font-medium mb-1">Discount (%)</label>
                <input type="number" value={discount} onChange={e=>setDiscount(e.target.value)} className="w-full p-3 border rounded-lg outline-none focus:ring-2 focus:ring-brand-500" placeholder="20"/>
            </div>
            {error && <p className="text-red-500 text-sm">{error}</p>}
        </div>

        <div className="bg-brand-600 text-white p-6 rounded-xl shadow-md flex flex-col justify-center items-center text-center">
            <p className="text-brand-200 text-sm uppercase font-bold mb-2">Final Price</p>
            <p className="text-4xl font-extrabold mb-4">${finalPrice.toFixed(2)}</p>
            <div className="bg-white/10 px-4 py-2 rounded-lg">
                <p className="text-sm">You Save: <span className="font-bold">${saved.toFixed(2)}</span></p>
            </div>
        </div>
    </div>
  );
};

export const SalesTaxCalculator: React.FC = () => {
  const [price, setPrice] = useState<string>('');
  const [rate, setRate] = useState<string>('');
  const [quantity, setQuantity] = useState<string>('1');
  const [result, setResult] = useState<{ tax: number; total: number; net: number } | null>(null);
  const [error, setError] = useState<string>('');
  const [copied, setCopied] = useState(false);

  const calculate = () => {
    setError('');
    setResult(null);

    const p = parseFloat(price);
    const r = parseFloat(rate);
    const q = quantity === '' ? 1 : parseFloat(quantity);

    if (isNaN(p) || p < 0) {
        setError('Please enter a valid item price.');
        return;
    }
    if (isNaN(r) || r < 0) {
        setError('Please enter a valid tax rate.');
        return;
    }
    if (isNaN(q) || q <= 0) {
        setError('Please enter a valid quantity (1 or more).');
        return;
    }

    const taxPerItem = p * (r / 100);
    const totalPerItem = p + taxPerItem;
    
    setResult({
        net: p * q,
        tax: taxPerItem * q,
        total: totalPerItem * q
    });
  };

  const reset = () => {
    setPrice('');
    setRate('');
    setQuantity('1');
    setResult(null);
    setError('');
  };

  const handleDownload = () => {
      if (!result) return;
      const text = `Sales Tax Report\n================\nItem Price: $${price}\nTax Rate: ${rate}%\nQuantity: ${quantity}\n\nNet Amount: $${result.net.toFixed(2)}\nSales Tax: $${result.tax.toFixed(2)}\nTotal Amount: $${result.total.toFixed(2)}\n\nGenerated by ToolMaster Pro`;
      const blob = new Blob([text], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'tax-report.txt';
      a.click();
      URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
      if (!result) return;
      const text = `Price: $${price} | Rate: ${rate}% | Qty: ${quantity}\nTotal: $${result.total.toFixed(2)} (Tax: $${result.tax.toFixed(2)})`;
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
      {/* Inputs */}
      <div className="space-y-6">
         <div className="grid grid-cols-2 gap-4">
             <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Item Price ($)</label>
                <div className="relative">
                    <DollarSign className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                    <input 
                        type="number" 
                        value={price}
                        onChange={(e) => setPrice(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                        placeholder="0.00"
                        min="0"
                    />
                </div>
             </div>
             <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Tax Rate (%)</label>
                <div className="relative">
                    <Percent className="w-4 h-4 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2" />
                    <input 
                        type="number" 
                        value={rate}
                        onChange={(e) => setRate(e.target.value)}
                        className="w-full pl-4 pr-10 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                        placeholder="e.g. 8.25"
                        min="0"
                        step="0.01"
                    />
                </div>
             </div>
         </div>

         <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Quantity <span className="text-slate-400 font-normal">(Optional)</span></label>
            <input 
                type="number" 
                value={quantity}
                onChange={(e) => setQuantity(e.target.value)}
                className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                placeholder="1"
                min="1"
            />
         </div>

         {error && (
            <div className="flex items-center gap-2 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-100 animate-in fade-in">
                <AlertCircle className="w-4 h-4 shrink-0" /> {error}
            </div>
         )}

         <div className="flex gap-3 pt-2">
            <button 
                onClick={calculate} 
                className="flex-1 bg-brand-600 text-white py-3 rounded-lg font-bold hover:bg-brand-700 transition-all shadow-lg hover:shadow-brand-200 active:scale-[0.98]"
            >
                Calculate Tax
            </button>
            <button 
                onClick={reset} 
                className="px-4 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 transition hover:text-slate-800 border border-slate-200" 
                title="Reset Inputs"
            >
                <RefreshCw className="w-5 h-5" />
            </button>
         </div>
      </div>

      {/* Result */}
      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col justify-center min-h-[300px]">
         {result ? (
            <div className="space-y-6 animate-in fade-in zoom-in duration-300">
                <div className="text-center pb-6 border-b border-slate-100">
                   <p className="text-sm text-slate-500 uppercase tracking-wide font-bold mb-1">Total Amount</p>
                   <p className="text-5xl font-extrabold text-slate-800">${result.total.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</p>
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                   <div className="bg-slate-50 p-4 rounded-lg text-center">
                      <p className="text-xs text-slate-500 uppercase font-bold mb-1">Sales Tax</p>
                      <p className="text-xl font-bold text-red-600">+${result.tax.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</p>
                   </div>
                   <div className="bg-slate-50 p-4 rounded-lg text-center">
                      <p className="text-xs text-slate-500 uppercase font-bold mb-1">Net Amount</p>
                      <p className="text-xl font-bold text-slate-700">${result.net.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</p>
                   </div>
                </div>

                {(parseFloat(quantity) > 1) && (
                    <div className="text-center text-sm text-slate-400">
                        Price per item: ${(result.total / parseFloat(quantity)).toFixed(2)} (incl. tax)
                    </div>
                )}
                
                <div className="flex gap-3 pt-2">
                    <button 
                        onClick={handleCopy}
                        className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-700 hover:bg-slate-200 transition"
                    >
                        {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                        {copied ? 'Copied' : 'Copy Result'}
                    </button>
                    <button 
                        onClick={handleDownload}
                        className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-700 hover:bg-slate-200 transition"
                    >
                        <Download className="w-4 h-4" /> Report
                    </button>
                </div>
            </div>
         ) : (
            <div className="text-center text-slate-400 opacity-60">
                <DollarSign className="w-16 h-16 mx-auto mb-4 bg-slate-100 rounded-full p-4" />
                <p className="font-medium">Enter details to calculate sales tax</p>
            </div>
         )}
      </div>
    </div>
  );
};

export const GSTCalculator: React.FC = () => {
  const [price, setPrice] = useState<string>('');
  const [rate, setRate] = useState<string>('');
  const [quantity, setQuantity] = useState<string>('1');
  const [result, setResult] = useState<{ gst: number; total: number; net: number } | null>(null);
  const [error, setError] = useState<string>('');
  const [copied, setCopied] = useState(false);

  const calculate = () => {
    setError('');
    setResult(null);

    const p = parseFloat(price);
    const r = parseFloat(rate);
    const q = quantity === '' ? 1 : parseFloat(quantity);

    if (isNaN(p) || p < 0) {
        setError('Please enter a valid item price.');
        return;
    }
    if (isNaN(r) || r < 0) {
        setError('Please enter a valid GST rate.');
        return;
    }
    if (isNaN(q) || q <= 0) {
        setError('Please enter a valid quantity (1 or more).');
        return;
    }

    const gstPerItem = p * (r / 100);
    const totalPerItem = p + gstPerItem;
    
    setResult({
        net: p * q,
        gst: gstPerItem * q,
        total: totalPerItem * q
    });
  };

  const reset = () => {
    setPrice('');
    setRate('');
    setQuantity('1');
    setResult(null);
    setError('');
  };

  const handleDownload = () => {
      if (!result) return;
      const text = `GST Report\n==========\nItem Price: $${price}\nGST Rate: ${rate}%\nQuantity: ${quantity}\n\nNet Amount: $${result.net.toFixed(2)}\nGST Amount: $${result.gst.toFixed(2)}\nTotal Amount: $${result.total.toFixed(2)}\n\nGenerated by ToolMaster Pro`;
      const blob = new Blob([text], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'gst-report.txt';
      a.click();
      URL.revokeObjectURL(url);
  };

  const handleCopy = () => {
      if (!result) return;
      const text = `Price: $${price} | Rate: ${rate}% | Qty: ${quantity}\nTotal: $${result.total.toFixed(2)} (GST: $${result.gst.toFixed(2)})`;
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
      {/* Inputs */}
      <div className="space-y-6">
         <div className="grid grid-cols-2 gap-4">
             <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">Item Price ($)</label>
                <div className="relative">
                    <DollarSign className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                    <input 
                        type="number" 
                        value={price}
                        onChange={(e) => setPrice(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                        placeholder="0.00"
                        min="0"
                    />
                </div>
             </div>
             <div>
                <label className="block text-sm font-medium text-slate-700 mb-1">GST Rate (%)</label>
                <div className="relative">
                    <Percent className="w-4 h-4 text-slate-400 absolute right-3 top-1/2 -translate-y-1/2" />
                    <input 
                        type="number" 
                        value={rate}
                        onChange={(e) => setRate(e.target.value)}
                        className="w-full pl-4 pr-10 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                        placeholder="e.g. 18"
                        min="0"
                        step="0.01"
                    />
                </div>
             </div>
         </div>

         <div>
            <label className="block text-sm font-medium text-slate-700 mb-1">Quantity <span className="text-slate-400 font-normal">(Optional)</span></label>
            <input 
                type="number" 
                value={quantity}
                onChange={(e) => setQuantity(e.target.value)}
                className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                placeholder="1"
                min="1"
            />
         </div>

         {error && (
            <div className="flex items-center gap-2 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-100 animate-in fade-in">
                <AlertCircle className="w-4 h-4 shrink-0" /> {error}
            </div>
         )}

         <div className="flex gap-3 pt-2">
            <button 
                onClick={calculate} 
                className="flex-1 bg-brand-600 text-white py-3 rounded-lg font-bold hover:bg-brand-700 transition-all shadow-lg hover:shadow-brand-200 active:scale-[0.98]"
            >
                Calculate GST
            </button>
            <button 
                onClick={reset} 
                className="px-4 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 transition hover:text-slate-800 border border-slate-200" 
                title="Reset Inputs"
            >
                <RefreshCw className="w-5 h-5" />
            </button>
         </div>
      </div>

      {/* Result */}
      <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col justify-center min-h-[300px]">
         {result ? (
            <div className="space-y-6 animate-in fade-in zoom-in duration-300">
                <div className="text-center pb-6 border-b border-slate-100">
                   <p className="text-sm text-slate-500 uppercase tracking-wide font-bold mb-1">Total Amount (Inc. GST)</p>
                   <p className="text-5xl font-extrabold text-slate-800">${result.total.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</p>
                </div>
                
                <div className="grid grid-cols-2 gap-4">
                   <div className="bg-slate-50 p-4 rounded-lg text-center">
                      <p className="text-xs text-slate-500 uppercase font-bold mb-1">GST Amount</p>
                      <p className="text-xl font-bold text-indigo-600">+${result.gst.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</p>
                   </div>
                   <div className="bg-slate-50 p-4 rounded-lg text-center">
                      <p className="text-xs text-slate-500 uppercase font-bold mb-1">Net Amount</p>
                      <p className="text-xl font-bold text-slate-700">${result.net.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</p>
                   </div>
                </div>

                {(parseFloat(quantity) > 1) && (
                    <div className="text-center text-sm text-slate-400">
                        Price per item: ${(result.total / parseFloat(quantity)).toFixed(2)} (incl. GST)
                    </div>
                )}
                
                <div className="flex gap-3 pt-2">
                    <button 
                        onClick={handleCopy}
                        className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-700 hover:bg-slate-200 transition"
                    >
                        {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                        {copied ? 'Copied' : 'Copy Result'}
                    </button>
                    <button 
                        onClick={handleDownload}
                        className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-700 hover:bg-slate-200 transition"
                    >
                        <Download className="w-4 h-4" /> Report
                    </button>
                </div>
            </div>
         ) : (
            <div className="text-center text-slate-400 opacity-60">
                <DollarSign className="w-16 h-16 mx-auto mb-4 bg-slate-100 rounded-full p-4" />
                <p className="font-medium">Enter price and GST rate</p>
            </div>
         )}
      </div>
    </div>
  );
};

export const MarginCalculator: React.FC = () => {
  const [cost, setCost] = useState<string>('');
  const [salePrice, setSalePrice] = useState<string>('');
  const [quantity, setQuantity] = useState<string>('1');
  const [result, setResult] = useState<{ profit: number; margin: number; totalProfit: number } | null>(null);
  const [error, setError] = useState<string>('');
  const [copied, setCopied] = useState(false);

  const calculate = () => {
    setError('');
    setResult(null);

    const c = parseFloat(cost);
    const s = parseFloat(salePrice);
    const q = quantity === '' ? 1 : parseFloat(quantity);

    if (isNaN(c) || c < 0) {
        setError('Please enter a valid cost price (0 or more).');
        return;
    }
    if (isNaN(s) || s < 0) {
        setError('Please enter a valid selling price (0 or more).');
        return;
    }
    if (isNaN(q) || q <= 0) {
        setError('Please enter a valid quantity (1 or more).');
        return;
    }

    const profit = s - c;
    let margin = 0;
    if (s > 0) {
        margin = (profit / s) * 100;
    } else if (c > 0) {
        margin = -100;
    }

    setResult({
        profit: profit,
        margin: margin,
        totalProfit: profit * q
    });
  };

  const reset = () => {
    setCost('');
    setSalePrice('');
    setQuantity('1');
    setResult(null);
    setError('');
  };

  const handleCopy = () => {
      if (!result) return;
      const text = `Margin Calculation\nCost: $${cost}\nPrice: $${salePrice}\nProfit: $${result.profit.toFixed(2)}\nMargin: ${result.margin.toFixed(2)}%`;
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
      if (!result) return;
      const text = `Profit Margin Report\n====================\nCost Price: $${cost}\nSelling Price: $${salePrice}\nQuantity: ${quantity}\n\nUnit Profit: $${result.profit.toFixed(2)}\nMargin: ${result.margin.toFixed(2)}%\nTotal Profit: $${result.totalProfit.toFixed(2)}\n\nGenerated by ToolMaster Pro`;
      const blob = new Blob([text], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'margin-report.txt';
      a.click();
      URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8">
       <div className="space-y-6">
          <div className="grid grid-cols-2 gap-4">
              <div>
                 <label className="block text-sm font-medium text-slate-700 mb-1">Cost Price ($)</label>
                 <div className="relative">
                    <DollarSign className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                    <input 
                        type="number" 
                        value={cost}
                        onChange={(e) => setCost(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                        placeholder="0.00"
                        min="0"
                    />
                 </div>
              </div>
              <div>
                 <label className="block text-sm font-medium text-slate-700 mb-1">Selling Price ($)</label>
                 <div className="relative">
                    <DollarSign className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2" />
                    <input 
                        type="number" 
                        value={salePrice}
                        onChange={(e) => setSalePrice(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                        placeholder="0.00"
                        min="0"
                    />
                 </div>
              </div>
          </div>

          <div>
             <label className="block text-sm font-medium text-slate-700 mb-1">Quantity <span className="text-slate-400 font-normal">(Optional)</span></label>
             <input 
                 type="number" 
                 value={quantity}
                 onChange={(e) => setQuantity(e.target.value)}
                 className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none transition"
                 placeholder="1"
                 min="1"
             />
          </div>

          {error && (
             <div className="flex items-center gap-2 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-100 animate-in fade-in">
                 <AlertCircle className="w-4 h-4 shrink-0" /> {error}
             </div>
          )}

          <div className="flex gap-3 pt-2">
             <button 
                 onClick={calculate} 
                 className="flex-1 bg-brand-600 text-white py-3 rounded-lg font-bold hover:bg-brand-700 transition-all shadow-lg hover:shadow-brand-200 active:scale-[0.98]"
             >
                 Calculate Margin
             </button>
             <button 
                 onClick={reset} 
                 className="px-4 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 transition hover:text-slate-800 border border-slate-200" 
                 title="Reset Inputs"
             >
                 <RefreshCw className="w-5 h-5" />
             </button>
          </div>
       </div>

       <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm flex flex-col justify-center min-h-[300px]">
          {result ? (
             <div className="space-y-6 animate-in fade-in zoom-in duration-300">
                 <div className="text-center pb-6 border-b border-slate-100">
                    <p className="text-sm text-slate-500 uppercase tracking-wide font-bold mb-1">Profit Margin</p>
                    <p className={`text-5xl font-extrabold ${result.margin >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{result.margin.toFixed(2)}%</p>
                 </div>
                 
                 <div className="grid grid-cols-2 gap-4">
                    <div className="bg-slate-50 p-4 rounded-lg text-center">
                       <p className="text-xs text-slate-500 uppercase font-bold mb-1">Unit Profit</p>
                       <p className={`text-xl font-bold ${result.profit >= 0 ? 'text-slate-700' : 'text-red-600'}`}>${result.profit.toFixed(2)}</p>
                    </div>
                    <div className="bg-slate-50 p-4 rounded-lg text-center">
                       <p className="text-xs text-slate-500 uppercase font-bold mb-1">Total Profit</p>
                       <p className={`text-xl font-bold ${result.totalProfit >= 0 ? 'text-brand-700' : 'text-red-600'}`}>${result.totalProfit.toFixed(2)}</p>
                    </div>
                 </div>

                 <div className="flex gap-3 pt-2">
                     <button 
                         onClick={handleCopy}
                         className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-700 hover:bg-slate-200 transition"
                     >
                         {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                         {copied ? 'Copied' : 'Copy Result'}
                     </button>
                     <button 
                         onClick={handleDownload}
                         className="flex-1 flex items-center justify-center gap-2 py-2 rounded-lg text-sm font-medium bg-slate-100 text-slate-700 hover:bg-slate-200 transition"
                     >
                         <Download className="w-4 h-4" /> Report
                     </button>
                 </div>
             </div>
          ) : (
             <div className="text-center text-slate-400 opacity-60">
                 <TrendingUp className="w-16 h-16 mx-auto mb-4 bg-slate-100 rounded-full p-4" />
                 <p className="font-medium">Enter Cost & Price to calculate</p>
             </div>
          )}
       </div>
    </div>
  );
}

export const FinancialCalculator: React.FC<{type: 'sales' | 'discount' | 'margin' | 'gst' | 'paypal'}> = ({type}) => {
  if (type === 'paypal') return <PayPalCalculator />;
  if (type === 'sales') return <SalesTaxCalculator />;
  if (type === 'margin') return <MarginCalculator />;
  if (type === 'gst') return <GSTCalculator />;
  if (type === 'discount') return <DiscountCalculator />;
  return null;
};

export const CurrencyConverter: React.FC = () => {
    const [amount, setAmount] = useState<string>('1');
    const [fromCurrency, setFromCurrency] = useState('USD');
    const [toCurrency, setToCurrency] = useState('EUR');
    const [rates, setRates] = useState<Record<string, number>>({});
    const [lastUpdate, setLastUpdate] = useState<string>('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [copied, setCopied] = useState(false);

    // Common fallback list if API fails or hasn't loaded
    const COMMON_CURRENCIES = [
        "USD", "EUR", "GBP", "JPY", "AUD", "CAD", "CHF", "CNY", "HKD", "NZD", 
        "SEK", "KRW", "SGD", "NOK", "MXN", "INR", "RUB", "ZAR", "TRY", "BRL", 
        "TWD", "DKK", "PLN", "THB", "IDR", "HUF", "CZK", "ILS", "CLP", "PHP", 
        "AED", "COP", "SAR", "MYR", "RON", "VND", "NGN"
    ];

    const currencies = Object.keys(rates).length > 0 ? Object.keys(rates).sort() : COMMON_CURRENCIES.sort();

    useEffect(() => {
        const fetchRates = async () => {
            if (!fromCurrency) return;
            setLoading(true);
            setError('');
            try {
                // Using a free public API that doesn't require a key for basic frontend demos
                const res = await fetch(`https://open.er-api.com/v6/latest/${fromCurrency}`);
                const data = await res.json();
                
                if (data.result === 'success') {
                    setRates(data.rates);
                    // Simple date formatting
                    const date = new Date(data.time_last_update_utc);
                    setLastUpdate(date.toLocaleString());
                } else {
                    setError('Could not fetch exchange rates.');
                }
            } catch (e) {
                setError('Network error: Could not connect to exchange rate service.');
            } finally {
                setLoading(false);
            }
        };
        
        fetchRates();
        
        // Refresh every minute if window is focused could be added here, but sticking to simple Effect
    }, [fromCurrency]);

    const handleSwap = () => {
        const temp = fromCurrency;
        setFromCurrency(toCurrency);
        setToCurrency(temp);
    };

    const getConvertedAmount = () => {
        const val = parseFloat(amount);
        if (isNaN(val)) return 0;
        const rate = rates[toCurrency] || 0;
        return val * rate;
    };

    const convertedAmount = getConvertedAmount();
    const currentRate = rates[toCurrency] || 0;

    const handleCopy = () => {
        const text = `${amount} ${fromCurrency} = ${convertedAmount.toFixed(2)} ${toCurrency}\nRate: 1 ${fromCurrency} = ${currentRate.toFixed(4)} ${toCurrency}`;
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const text = `Currency Conversion Report\n==========================\nFrom: ${amount} ${fromCurrency}\nTo:   ${convertedAmount.toFixed(2)} ${toCurrency}\n\nExchange Rate: 1 ${fromCurrency} = ${currentRate.toFixed(6)} ${toCurrency}\nLast Updated: ${lastUpdate}\n\nGenerated by ToolMaster Pro`;
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `conversion-${fromCurrency}-${toCurrency}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const formatCurrency = (val: number, currency: string) => {
        try {
            return new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(val);
        } catch {
            return `${currency} ${val.toFixed(2)}`;
        }
    };

    return (
        <div className="max-w-4xl mx-auto bg-white p-8 rounded-xl shadow-sm border border-slate-200">
             <div className="flex items-center justify-between mb-8 pb-4 border-b border-slate-100">
                <div className="flex items-center gap-3">
                    <div className="p-3 bg-brand-50 text-brand-600 rounded-lg">
                        <Globe className="w-6 h-6" />
                    </div>
                    <div>
                        <h2 className="text-xl font-bold text-slate-800">Real-Time Converter</h2>
                        <p className="text-xs text-slate-400">Rates updated: {lastUpdate || 'Loading...'}</p>
                    </div>
                </div>
                <button onClick={() => {setAmount('1'); setFromCurrency('USD'); setToCurrency('EUR');}} className="text-slate-400 hover:text-brand-600 transition">
                    <RefreshCw className="w-5 h-5" />
                </button>
             </div>

             <div className="grid md:grid-cols-7 gap-4 items-center">
                {/* From Section */}
                <div className="md:col-span-3 space-y-2">
                    <label className="block text-xs font-bold text-slate-500 uppercase">Amount</label>
                    <input 
                        type="number" 
                        value={amount}
                        onChange={(e) => setAmount(e.target.value)}
                        className="w-full p-3 text-lg border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none font-semibold"
                        placeholder="1.00"
                        min="0"
                    />
                    <select 
                        value={fromCurrency}
                        onChange={(e) => setFromCurrency(e.target.value)}
                        className="w-full p-2 border border-slate-200 rounded-lg bg-slate-50 text-sm text-slate-700 font-medium"
                    >
                        {currencies.map(c => <option key={c} value={c}>{c}</option>)}
                    </select>
                </div>

                {/* Swap Button */}
                <div className="md:col-span-1 flex justify-center py-4 md:py-0">
                    <button 
                        onClick={handleSwap}
                        className="p-3 rounded-full bg-slate-100 text-slate-600 hover:bg-brand-100 hover:text-brand-600 transition shadow-sm border border-slate-200"
                        title="Swap Currencies"
                    >
                        <ArrowRightLeft className="w-5 h-5" />
                    </button>
                </div>

                {/* To Section */}
                <div className="md:col-span-3 space-y-2">
                    <label className="block text-xs font-bold text-slate-500 uppercase">Converted To</label>
                    <div className="relative">
                        <div className="w-full p-3 text-lg border border-brand-200 bg-brand-50/50 rounded-lg font-bold text-brand-900 truncate">
                            {loading ? '...' : formatCurrency(convertedAmount, toCurrency)}
                        </div>
                    </div>
                    <select 
                        value={toCurrency}
                        onChange={(e) => setToCurrency(e.target.value)}
                        className="w-full p-2 border border-slate-200 rounded-lg bg-slate-50 text-sm text-slate-700 font-medium"
                    >
                        {currencies.map(c => <option key={c} value={c}>{c}</option>)}
                    </select>
                </div>
             </div>

             {/* Rate Info */}
             <div className="mt-8 p-4 bg-slate-50 rounded-xl border border-slate-100 flex flex-col md:flex-row justify-between items-center gap-4">
                <div className="text-center md:text-left">
                    <p className="text-sm text-slate-500 font-medium mb-1">Current Exchange Rate</p>
                    <p className="text-lg font-bold text-slate-800">
                        1 {fromCurrency} = <span className="text-brand-600">{currentRate.toFixed(4)} {toCurrency}</span>
                    </p>
                </div>
                <div className="flex gap-2">
                    <button 
                        onClick={handleCopy}
                        className="flex items-center gap-2 px-4 py-2 bg-white border border-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50 text-slate-700 transition"
                    >
                        {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                        {copied ? 'Copied' : 'Copy'}
                    </button>
                    <button 
                        onClick={handleDownload}
                        className="flex items-center gap-2 px-4 py-2 bg-brand-600 text-white rounded-lg text-sm font-medium hover:bg-brand-700 transition shadow-sm"
                    >
                        <Download className="w-4 h-4" /> Save
                    </button>
                </div>
             </div>

             {error && (
                <div className="mt-4 p-3 bg-red-50 text-red-700 text-sm rounded-lg flex items-center gap-2">
                    <AlertCircle className="w-4 h-4" /> {error}
                </div>
             )}
        </div>
    );
}

export const BinaryCalculator: React.FC = () => {
  const [bin1, setBin1] = useState('');
  const [bin2, setBin2] = useState('');
  const [op, setOp] = useState('ADD');
  const [res, setRes] = useState<{bin: string, dec: number} | null>(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const validateBinary = (val: string) => /^[01]*$/.test(val);

  const handleInput1 = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (validateBinary(e.target.value)) setBin1(e.target.value);
  };

  const handleInput2 = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (validateBinary(e.target.value)) setBin2(e.target.value);
  };

  const calculate = () => {
    setError('');
    setRes(null);

    if (!bin1) {
        setError('Please enter the first binary number.');
        return;
    }
    if (op !== 'NOT' && !bin2) {
        setError('Please enter the second binary number.');
        return;
    }

    const n1 = parseInt(bin1, 2);
    const n2 = op !== 'NOT' ? parseInt(bin2, 2) : 0;

    if (isNaN(n1)) { setError('Invalid binary input 1'); return; }
    if (op !== 'NOT' && isNaN(n2)) { setError('Invalid binary input 2'); return; }

    let r = 0;
    switch (op) {
      case 'ADD': r = n1 + n2; break;
      case 'SUB': r = n1 - n2; break;
      case 'MUL': r = n1 * n2; break;
      case 'DIV': 
        if (n2 === 0) { setError('Cannot divide by zero.'); return; }
        r = Math.floor(n1 / n2); 
        break;
      case 'AND': r = n1 & n2; break;
      case 'OR': r = n1 | n2; break;
      case 'XOR': r = n1 ^ n2; break;
      case 'NOT': r = ~n1; break;
    }

    setRes({ bin: (r >>> 0).toString(2), dec: r });
  };

  const reset = () => {
    setBin1('');
    setBin2('');
    setOp('ADD');
    setRes(null);
    setError('');
  };

  const copyResult = () => {
    if (res) {
        navigator.clipboard.writeText(res.bin);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="max-w-2xl mx-auto bg-white p-8 rounded-xl border border-slate-200 shadow-sm">
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4 items-end mb-6">
            <div className="md:col-span-2">
                <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Binary Input 1</label>
                <div className="relative">
                    <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-slate-400 font-mono">0b</span>
                    <input 
                        type="text" 
                        value={bin1} 
                        onChange={handleInput1} 
                        className="w-full pl-8 pr-4 py-2 border border-slate-300 rounded-lg font-mono focus:ring-2 focus:ring-brand-500 outline-none" 
                        placeholder="1010"
                    />
                </div>
            </div>
            <div className="md:col-span-1">
                 <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Operation</label>
                 <select 
                    value={op} 
                    onChange={(e) => setOp(e.target.value)} 
                    className="w-full p-2 border border-slate-300 rounded-lg bg-slate-50 font-bold text-center text-sm focus:ring-2 focus:ring-brand-500 outline-none"
                 >
                    <option value="ADD">+</option>
                    <option value="SUB">-</option>
                    <option value="MUL">×</option>
                    <option value="DIV">÷</option>
                    <option value="AND">AND</option>
                    <option value="OR">OR</option>
                    <option value="XOR">XOR</option>
                    <option value="NOT">NOT (~)</option>
                </select>
            </div>
            <div className="md:col-span-2">
                <label className={`block text-xs font-bold uppercase mb-1 ${op === 'NOT' ? 'text-slate-300' : 'text-slate-500'}`}>Binary Input 2</label>
                <div className="relative">
                    <span className={`absolute left-3 top-1/2 -translate-y-1/2 text-xs font-mono ${op === 'NOT' ? 'text-slate-200' : 'text-slate-400'}`}>0b</span>
                    <input 
                        type="text" 
                        value={bin2} 
                        onChange={handleInput2} 
                        disabled={op === 'NOT'}
                        className={`w-full pl-8 pr-4 py-2 border rounded-lg font-mono focus:ring-2 focus:ring-brand-500 outline-none ${op === 'NOT' ? 'bg-slate-50 border-slate-100 text-slate-300' : 'bg-white border-slate-300'}`}
                        placeholder="0101"
                    />
                </div>
            </div>
        </div>

        {error && (
            <div className="flex items-center gap-2 mb-6 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-100 animate-in fade-in">
                <AlertCircle className="w-4 h-4 shrink-0" /> {error}
            </div>
        )}

        <div className="flex gap-3 mb-8">
            <button 
                onClick={calculate} 
                className="flex-1 bg-brand-600 text-white py-3 rounded-lg font-bold hover:bg-brand-700 transition shadow-lg hover:shadow-brand-200"
            >
                Calculate Result
            </button>
            <button 
                onClick={reset} 
                className="px-4 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 transition hover:text-slate-800 border border-slate-200"
            >
                <RefreshCw className="w-5 h-5" />
            </button>
        </div>

        {res && (
            <div className="bg-slate-900 text-green-400 p-6 rounded-xl font-mono text-center relative overflow-hidden animate-in zoom-in duration-300">
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-green-500 to-blue-500"></div>
                <div className="text-xs text-slate-500 uppercase tracking-widest mb-2">Binary Result</div>
                <div className="text-3xl font-bold mb-4 break-all">{res.bin}</div>
                
                <div className="flex items-center justify-center gap-4">
                    <div className="inline-block bg-white/10 px-3 py-1 rounded text-sm text-slate-300">
                        Decimal: <span className="text-white font-bold">{res.dec}</span>
                    </div>
                    <button 
                        onClick={copyResult}
                        className="flex items-center gap-2 text-xs bg-white/10 hover:bg-white/20 text-white px-3 py-1 rounded transition"
                    >
                        {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                        {copied ? 'Copied' : 'Copy'}
                    </button>
                </div>
            </div>
        )}
        
        {!res && (
            <div className="text-center text-slate-400 py-8">
                <Binary className="w-12 h-12 mx-auto mb-3 opacity-20" />
                <p className="text-sm">Enter binary numbers to perform calculations</p>
            </div>
        )}
    </div>
  )
}

export const FibonacciCalculator: React.FC = () => {
  const [terms, setTerms] = useState<string>('10');
  const [first, setFirst] = useState<string>('0');
  const [second, setSecond] = useState<string>('1');
  const [sequence, setSequence] = useState<string[]>([]);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const calculate = () => {
    setError('');
    setSequence([]);
    
    const n = parseInt(terms);
    const f0 = parseInt(first);
    const f1 = parseInt(second);

    if (isNaN(n) || n <= 0) {
        setError('Please enter a valid number of terms (1 or more).');
        return;
    }
    if (isNaN(f0)) {
        setError('Please enter a valid first number.');
        return;
    }
    if (isNaN(f1)) {
        setError('Please enter a valid second number.');
        return;
    }

    if (n > 1000) {
        setError('Maximum 1000 terms allowed to prevent browser freeze. (Use smaller count for better performance)');
        return;
    }

    // Use BigInt for potentially large numbers
    const seq: bigint[] = [];
    try {
        if (n >= 1) seq.push(BigInt(f0));
        if (n >= 2) seq.push(BigInt(f1));

        for (let i = 2; i < n; i++) {
            seq.push(seq[i - 1] + seq[i - 2]);
        }
        setSequence(seq.map(String));
    } catch (e) {
        setError('Numbers too large to process.');
    }
  };

  const reset = () => {
    setTerms('10');
    setFirst('0');
    setSecond('1');
    setSequence([]);
    setError('');
  };

  const handleCopy = () => {
      if (sequence.length === 0) return;
      navigator.clipboard.writeText(sequence.join(', '));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
      if (sequence.length === 0) return;
      const text = `Fibonacci Sequence Report\n=========================\nTerms: ${terms}\nStart Sequence: ${first}, ${second}\n\nOutput:\n${sequence.join(', ')}\n\nGenerated by ToolMaster Pro`;
      const blob = new Blob([text], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'fibonacci-sequence.txt';
      a.click();
      URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-3xl mx-auto space-y-8">
        {/* Inputs */}
        <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
            <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                <Calculator className="w-5 h-5 text-brand-600" /> Configuration
            </h3>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Number of Terms (n)</label>
                    <input 
                        type="number" 
                        value={terms}
                        onChange={(e) => setTerms(e.target.value)}
                        className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none"
                        placeholder="10"
                        min="1"
                        max="1000"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">First Term (Optional)</label>
                    <input 
                        type="number" 
                        value={first}
                        onChange={(e) => setFirst(e.target.value)}
                        className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none bg-slate-50"
                        placeholder="0"
                    />
                </div>
                <div>
                    <label className="block text-sm font-medium text-slate-700 mb-1">Second Term (Optional)</label>
                    <input 
                        type="number" 
                        value={second}
                        onChange={(e) => setSecond(e.target.value)}
                        className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none bg-slate-50"
                        placeholder="1"
                    />
                </div>
            </div>

            {error && (
                <div className="flex items-center gap-2 mb-4 text-red-600 text-sm bg-red-50 p-3 rounded-lg border border-red-100">
                    <AlertCircle className="w-4 h-4 shrink-0" /> {error}
                </div>
            )}

            <div className="flex gap-3">
                <button onClick={calculate} className="flex-1 bg-brand-600 text-white py-2.5 rounded-lg font-bold hover:bg-brand-700 transition shadow-sm">
                    Generate Sequence
                </button>
                <button onClick={reset} className="px-4 bg-slate-100 text-slate-600 rounded-lg hover:bg-slate-200 transition border border-slate-200">
                    <RefreshCw className="w-5 h-5" />
                </button>
            </div>
        </div>

        {/* Results */}
        {sequence.length > 0 && (
            <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm animate-in fade-in slide-in-from-bottom-4">
                <div className="flex items-center justify-between mb-4">
                    <h3 className="font-bold text-slate-700">Sequence Output</h3>
                    <div className="flex gap-2">
                         <button 
                            onClick={handleCopy}
                            className="flex items-center gap-1 text-xs font-medium bg-slate-100 hover:bg-slate-200 px-3 py-1.5 rounded text-slate-600 transition"
                        >
                            {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />} {copied ? 'Copied' : 'Copy'}
                        </button>
                        <button 
                            onClick={handleDownload}
                            className="flex items-center gap-1 text-xs font-medium bg-slate-100 hover:bg-slate-200 px-3 py-1.5 rounded text-slate-600 transition"
                        >
                            <Download className="w-3 h-3" /> Download
                        </button>
                    </div>
                </div>

                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100 overflow-x-auto max-h-64 overflow-y-auto">
                    <div className="flex flex-wrap gap-2">
                        {sequence.map((num, idx) => (
                            <div key={idx} className="group relative">
                                <span className={`inline-block px-2 py-1 rounded text-sm font-mono ${idx === sequence.length - 1 ? 'bg-brand-100 text-brand-700 font-bold ring-1 ring-brand-200' : 'bg-white text-slate-600 border border-slate-200'}`}>
                                    {num}
                                </span>
                                <span className="absolute -top-6 left-1/2 -translate-x-1/2 bg-slate-800 text-white text-[10px] px-1.5 py-0.5 rounded opacity-0 group-hover:opacity-100 transition pointer-events-none">
                                    #{idx + 1}
                                </span>
                            </div>
                        ))}
                    </div>
                </div>
                
                <div className="mt-4 pt-4 border-t border-slate-100 flex justify-between items-center">
                    <div className="text-sm text-slate-500">
                        Total Terms: <span className="font-semibold text-slate-800">{sequence.length}</span>
                    </div>
                    {sequence.length > 0 && (
                        <div className="text-sm text-slate-500">
                            Last Term ({sequence.length}th): <span className="font-bold text-brand-600 font-mono">{sequence[sequence.length - 1].length > 15 ? sequence[sequence.length - 1].substring(0, 15) + '...' : sequence[sequence.length - 1]}</span>
                        </div>
                    )}
                </div>
            </div>
        )}
    </div>
  );
}

export const ConfidenceInterval: React.FC = () => {
    const [mean, setMean] = useState(0);
    const [stdDev, setStdDev] = useState(1);
    const [size, setSize] = useState(10);
    const [confidence, setConfidence] = useState(0.95);
    const [result, setResult] = useState<{lower: number, upper: number} | null>(null);

    const calc = () => {
        // Z-score approx
        let z = 1.96;
        if(confidence === 0.90) z = 1.645;
        if(confidence === 0.99) z = 2.576;
        
        const margin = z * (stdDev / Math.sqrt(size));
        setResult({lower: mean - margin, upper: mean + margin});
    }

    return (
        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            <div className="space-y-4 bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                <div><label className="block text-xs font-bold uppercase text-slate-500 mb-1">Sample Mean (x̄)</label><input type="number" value={mean} onChange={e=>setMean(+e.target.value)} className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none"/></div>
                <div><label className="block text-xs font-bold uppercase text-slate-500 mb-1">Standard Deviation (s)</label><input type="number" value={stdDev} onChange={e=>setStdDev(+e.target.value)} className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none"/></div>
                <div><label className="block text-xs font-bold uppercase text-slate-500 mb-1">Sample Size (n)</label><input type="number" value={size} onChange={e=>setSize(+e.target.value)} className="w-full p-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-brand-500 outline-none"/></div>
                <div>
                    <label className="block text-xs font-bold uppercase text-slate-500 mb-1">Confidence Level</label>
                    <select value={confidence} onChange={e=>setConfidence(+e.target.value)} className="w-full p-2 border border-slate-300 rounded-lg bg-white focus:ring-2 focus:ring-brand-500 outline-none">
                        <option value={0.90}>90%</option>
                        <option value={0.95}>95%</option>
                        <option value={0.99}>99%</option>
                    </select>
                </div>
                <button onClick={calc} className="w-full bg-brand-600 text-white py-3 rounded-lg font-bold hover:bg-brand-700 mt-2 transition">Calculate Interval</button>
            </div>
            <div className="flex items-center justify-center bg-slate-50 rounded-xl p-6 border border-slate-200">
                {result ? (
                    <div className="text-center">
                        <div className="text-sm text-slate-500 mb-2 font-medium uppercase tracking-wider">Confidence Interval</div>
                        <div className="text-3xl font-bold text-slate-800 mb-1">[{result.lower.toFixed(4)}, {result.upper.toFixed(4)}]</div>
                        <div className="text-sm text-slate-400">Margin of Error: ±{((result.upper - result.lower)/2).toFixed(4)}</div>
                    </div>
                ) : (
                    <div className="text-slate-400 text-center">
                        <p>Enter sample data to calculate the confidence interval.</p>
                    </div>
                )}
            </div>
        </div>
    )
}
